FROM --platform=linux/amd64 ubuntu:latest

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install build-essential && \
    apt-get -y install gcc && \
    apt-get -y install nasm && \
    apt-get -y install git